build = [
    "src/app.cream",
    "src/about.cream",
    "src/components/link.cream",
    "src/home.cream",
    "src/components/navbar.cream",
    "src/not_found.cream",
    "src/stdlib.cream",
    "src/docs.cream",
    "src/assets/github.png",
    "favicon.png"
]
port = 8000
root = "/cream_docs"

[packages]

[env]
